# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ch4ngeMe
    ports:
      - 17001:17001

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 1337:8080
